#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"

if [[ -f "${APP_DATA_DIR}/data/index.redb" ]]; then
    echo "index.redb exists. Removing..."
    rm -f "${APP_DATA_DIR}/data/index.redb"
else
    echo "Fresh install. No reindex needed."
fi

echo "Install completed successfully"