version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: nsecbunker_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
      
  web:
    image: pablof7z/nsecbunkerd
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/app/config
    environment:
      - DATABASE_URL=file:${APP_DATA_DIR}/data/nsecbunker.db
      - ADMIN_NPUBS=npub13azv2cf3kd3xdzcwqxlgcudjg7r9nzak37usnn7h374lkpvd6rcq4k8m54
    depends_on:
      - migrations

  migrations:
    image: pablof7z/nsecbunkerd
    volumes:
      - ${APP_DATA_DIR}/data:/app/config
    entrypoint: ""
    environment:
      - DATABASE_URL=file:${APP_DATA_DIR}/data/nsecbunker.db
      - ADMIN_NPUBS=npub13azv2cf3kd3xdzcwqxlgcudjg7r9nzak37usnn7h374lkpvd6rcq4k8m54
    command:
      - npx
      - prisma
      - migrate
      - deploy
