version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: trilium-notes_server_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: zadam/trilium:0.63.3@sha256:03c3f3cc8b8d63d11edf01b731b4cf1444fc89abea32e5001e49fdf66cbdd540
    restart: on-failure
    environment:
      - TRILIUM_DATA_DIR=/data
    volumes:
      - ${APP_DATA_DIR}/data:/data
